crypto_conseils_blog:
    resource: "@CryptoConseilsBlogBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: CryptoConseilsUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout